public_html/intranet/config/routes.rb
Rails.application.routes.draw do

  resources :noticias
  root 'capa#index'
  post 'interesse' => 'capa#createinteresse'
  post 'update_dashboard' => 'intranet/dashboard#update_index'
  get 'intranet' => 'intranet/sessions#new'
  namespace :intranet do
    resources :kind_of_posts do
      resources :posts
    end
    resources :users
    resources :posts
    resources :categories
    resources :dashboard
    resources :folhetos
    resources :clientes

    controller :sessions do
      get  'login' => :new
      post 'login' => :create
      delete 'logout' => :destroy
    end

    get 'sessions/create'
    get 'sessions/destroy'

    get 'admin' => 'admin#index'
    get 'logout' => 'sessions#destroy'

  end
  mount Ckeditor::Engine => '/ckeditor'

end

public_html/intranet/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

public_html/intranet/app/controllers/intranet/admin_controller.rb
class Intranet::AdminController < Intranet::IntranetController
  before_action :authorize
  def index
  end
end

public_html/intranet/app/controllers/intranet/capa_controller.rb
class Intranet::CapaController < Intranet::IntranetController
  before_action :authorize
  protect_from_forgery except: [:update_index]


  def index
    @date_filter = "30_dias"
    @visitors_by_date = nil
    @visitors = nil
    @sessions = nil
    @pageviews =  nil
    @avg_duration = nil
  end

  def update_index


    require 'google/api_client'
    require 'date'

    @date_filter = params[:date]
    service_account_email = 'analytics-intranet@api-project-359628520071.iam.gserviceaccount.com' # Email of service account
    key_file = 'config/API Project-6186e14a5b0a.p12' # File containing your private key
    key_secret = 'notasecret' # Password to unlock private key
    profile = 'ga:18033085' # Analytics profile ID.
    @client_id = 'ga:18033085'
    client = Google::APIClient.new(
      :application_name => 'API Project',
      :application_version => '1.0')

    key = Google::APIClient::KeyUtils.load_from_pkcs12(key_file, key_secret)
    client.authorization = Signet::OAuth2::Client.new(
        :token_credential_uri => 'https://accounts.google.com/o/oauth2/token',
        :audience => 'https://accounts.google.com/o/oauth2/token',
        :scope => 'https://www.googleapis.com/auth/analytics.readonly',
        :issuer => service_account_email,
        :signing_key => key)

    client.authorization.fetch_access_token!

    analytics = client.discovered_api('analytics','v3')

    if @date_filter == '30_dias'
      # start_date = Time.now - 1.month
      start_date = Date.today.last_month.strftime("%Y-%m-%d").to_s
      end_date = Date.today.strftime("%Y-%m-%d").to_s
      dimension = "ga:date"
    elsif @date_filter == '7_dias'
      start_date = Date.today.last_week.strftime("%Y-%m-%d").to_s
      end_date = Date.today.strftime("%Y-%m-%d").to_s
      dimension = "ga:date"
    else
      start_date = Date.yesterday.strftime("%Y-%m-%d").to_s
      end_date = Date.yesterday.strftime("%Y-%m-%d").to_s
      dimension = "ga:hour"
    end

    result = client.execute(:api_method => analytics.data.ga.get, :parameters => {
        'ids'        => profile,
        'start-date' => start_date,
        'end-date'   => end_date,
        'metrics'    => 'ga:visitors,ga:sessions,ga:pageviews,ga:avgSessionDuration',
    })
    result2 =  client.execute(:api_method => analytics.data.ga.get, :parameters => {
        'ids'        => profile,
        'start-date' => start_date,
        'end-date'   => end_date,
        'dimensions' => dimension,
        'metrics'    => 'ga:visitors',
    })


    @visitors_by_date = result2.data.rows

    @visitors = result.data.totalsForAllResults["ga:visitors"]
    @sessions = result.data.totalsForAllResults["ga:sessions"]
    @pageviews =  result.data.totalsForAllResults["ga:pageviews"]
    @avg_duration =  Time.at(result.data.totalsForAllResults["ga:avgSessionDuration"].to_f).utc.strftime("%H:%M:%S")

    respond_to do |format|
      format.js
    end

  end

end

public_html/intranet/app/controllers/intranet/categories_controller.rb
class Intranet::CategoriesController < Intranet::IntranetController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :authorize
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to intranet_categories_url, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to intranet_categories_url, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to intranet_categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :inativar, :Kind_of_post_id)
    end
end

public_html/intranet/app/controllers/intranet/clientes_controller.rb
class Intranet::ClientesController < Intranet::IntranetController

  before_action :authorize, except: [:create_from_contact]
  helper_method :sort_column, :sort_direction
  protect_from_forgery except: [:create_from_contact]

  #STATUS DO CLIENTE:   Aberto:  1
  #                     Em atendimento: 2
  #                     Encerrado: 3
  #                     Fechado: 4

  def index


    sort_column = params[:sort]
    sort_direction = params[:direction]
    @de = params[:de]
    @ate = params[:ate]
    @atendido_por = params[:atendido_por]
    @status = params[:status]
    @search = params[:search]
    if sort_direction == 'desc'
      @clientes = Cliente.search(params[:search]).order("#{sort_column} desc").search_status(@status).search_atendente(@atendido_por).search_data(@de,@ate).page(params[:page])
    elsif sort_direction == 'asc'
      @clientes = Cliente.search(params[:search]).order("#{sort_column} asc").search_status(@status).search_atendente(@atendido_por).search_data(@de,@ate).page(params[:page])
    else
      @clientes = Cliente.search(params[:search]).order("created_at desc").search_status(@status).search_atendente(@atendido_por).search_data(@de,@ate).page(params[:page])
    end

    respond_to do |format|
      format.html
      format.js
      format.pdf do
        data_de = @de.nil? ? "01/01/2016" : @de
        data_ate = @ate.nil? ? Time.now.strftime("%d/%m/%Y") : @ate
        pdf = Prawn::Document.new
        relatorio(pdf, data_de, data_ate ,@clientes)
        send_data pdf.render, filename: 'relatorio.pdf', type: 'application/pdf'
      end


    end



  end

  def relatorio(pdf, data_de, data_ate, clientes) # geração de relatorio para download

    pdf.image "#{Rails.root}/app/assets/images/logomarca-criativitta-menu.png", width: 130, height: 33, position: 405, vposition: 10
    pdf.text "RELATÓRIO DE LEADS - CRIATIVITTÁ"
    pdf.stroke_horizontal_rule
    pdf.move_down 20
    pdf.text "Período: " + data_de + " até " + data_ate
    pdf.move_down 20
    pdf.font_size 8

    data = [["Data", 'Nome', 'Telefone', 'Email', 'Interesse', 'Atendente', 'Status']]

    clientes.each do |c|
      status = ""
      case c.status
      when 1
        status = "Aberto"
      when 2
        status = "Em atendimento"
      when 3
        status = "Encerrado"
      when 4
        status = "Fechado"
      end
      data += [[c.created_at.strftime("%d/%m/%Y"), c.nome, c.telefone, c.email, c.interesse, c.atendido_por, status]]
    end

    pdf.table(data, header: true, column_widths: [55] )

  end



  def show
    @cliente = Cliente.find(params[:id])
  end

  def new
    @cliente = Cliente.new
  end

  def edit
    @cliente = Cliente.find(params[:id])
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to intranet_clientes_url, notice: 'Cliente foi criado com sucesso' }
        format.json { render action: 'show', status: :created, location: @cliente }
        format.js
      else
        format.html { render action: 'new' }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  def create_from_contact
    # implementar de acordo com os parametros que vier da view
    @curso_id = params[:id][0]
    @categoria_id = params[:categoria_id][0]
    @cliente = Cliente.new(cliente_params)

    if @cliente.valid?
      if verify_recaptcha(model: @cliente)
        if @cliente.save
          ContatoMailer.contato(@cliente.nome,@cliente.telefone,@cliente.email,@cliente.mensagem, @cliente.curso).deliver
          redirect_to  "/cursos/#{@curso_id}?id=#{@categoria_id}", notice: "Mensagem enviada com successo!"
        end
      else
        flash[:error] = "Por favor marque a opção 'Não sou um robô' antes de enviar."
        redirect_to "/cursos/#{@curso_id}?id=#{@categoria_id}"

      end
    else
      flash[:alert] = 'Alguns campos não foram preenchidos corretamente.'
      redirect_to "/cursos/#{@curso_id}?id=#{@categoria_id}"
    end
  end

  def update
    @cliente = Cliente.find(params[:id])

    if @cliente.update_attributes(cliente_params)
      redirect_to intranet_clientes_url, notice: 'Cliente atualizado com sucesso.'
    else
      render action: "edit"
    end
  end

  def destroy
    @cliente = Cliente.find(params[:id])
    @cliente.destroy

    redirect_to intranet_clientes_url, notice: 'Cliente excluido com sucesso.'
  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_cliente
    @cliente = Cliente.find(params[:id])
  end
  def sort_column
    params[:sort] || "id"
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def cliente_params
    params.require(:cliente).permit(:nome, :email, :telefone, :mensagem, :interesse, :status, :atendido_por)
  end

end

public_html/intranet/app/controllers/intranet/dashboard_controller.rb
class Intranet::DashboardController < Intranet::IntranetController

  before_action :authorize
  protect_from_forgery except: [:update_index]


  def index



    @date_filter = "30_dias"



    @visitors_by_date = nil

    @visitors = nil
    @sessions = nil
    @pageviews =  nil
    @avg_duration = nil

  end

  def update_index


    require 'google/api_client'
    require 'date'

    @date_filter = params[:date]
    service_account_email = 'analytics-intranet@api-project-359628520071.iam.gserviceaccount.com' # Email of service account
    key_file = 'config/API Project-6186e14a5b0a.p12' # File containing your private key
    key_secret = 'notasecret' # Password to unlock private key
    profile = 'ga:204329728' # Analytics profile ID = Criativittá.
    client = Google::APIClient.new(
      :application_name => 'API Project',
      :application_version => '1.0')

    key = Google::APIClient::KeyUtils.load_from_pkcs12(key_file, key_secret)
    client.authorization = Signet::OAuth2::Client.new(
        :token_credential_uri => 'https://accounts.google.com/o/oauth2/token',
        :audience => 'https://accounts.google.com/o/oauth2/token',
        :scope => 'https://www.googleapis.com/auth/analytics.readonly',
        :issuer => service_account_email,
        :signing_key => key)

    client.authorization.fetch_access_token!

    analytics = client.discovered_api('analytics','v3')

    if @date_filter == '30_dias'
      start_date = Date.today.last_month.strftime("%Y-%m-%d").to_s
      end_date = Date.today.strftime("%Y-%m-%d").to_s
      dimension = "ga:date"
    elsif @date_filter == '7_dias'
      start_date = Date.today.last_week.strftime("%Y-%m-%d").to_s
      end_date = Date.today.strftime("%Y-%m-%d").to_s
      dimension = "ga:date"
    else
      start_date = Date.yesterday.strftime("%Y-%m-%d").to_s
      end_date = Date.yesterday.strftime("%Y-%m-%d").to_s
      dimension = "ga:hour"
    end

    result = client.execute(:api_method => analytics.data.ga.get, :parameters => {
        'ids'        => profile,
        'start-date' => start_date,
        'end-date'   => end_date,
        'metrics'    => 'ga:visitors,ga:sessions,ga:pageviews,ga:avgSessionDuration',
    })
    result2 =  client.execute(:api_method => analytics.data.ga.get, :parameters => {
        'ids'        => profile,
        'start-date' => start_date,
        'end-date'   => end_date,
        'dimensions' => dimension,
        'metrics'    => 'ga:visitors',
    })


    @visitors_by_date = result2.data.rows

    @visitors = result.data.totalsForAllResults["ga:visitors"]
    @sessions = result.data.totalsForAllResults["ga:sessions"]
    @pageviews =  result.data.totalsForAllResults["ga:pageviews"]
    @avg_duration =  Time.at(result.data.totalsForAllResults["ga:avgSessionDuration"].to_f).utc.strftime("%H:%M:%S")

    respond_to do |format|
      format.js
    end

  end


end

public_html/intranet/app/controllers/intranet/folhetos_controller.rb
class Intranet::FolhetosController < Intranet::IntranetController
  before_action :authorize
  before_action :set_folheto, only: [:show, :edit, :update, :destroy]

  # GET /folhetos
  # GET /folhetos.json
  def index
    @folhetos = Folheto.all
  end

  # GET /folhetos/1
  # GET /folhetos/1.json
  def show
  end

  # GET /folhetos/new
  def new
    @folheto = Folheto.new
  end

  # GET /folhetos/1/edit
  def edit
  end

  # POST /folhetos
  # POST /folhetos.json
  def create
    @folheto = Folheto.new(folheto_params)

    respond_to do |format|
      if @folheto.save
        format.html { redirect_to new_intranet_folheto_path, notice: 'Folheto criado com sucesso.' }
        format.json { render :show, status: :created, location: @folheto }
      else
        format.html { render :new }
        format.json { render json: @folheto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /folhetos/1
  # PATCH/PUT /folhetos/1.json
  def update
    @folheto.remover_imagem_folheto(params[:remover_imagem_folheto])
    respond_to do |format|
      if @folheto.update(folheto_params)
        format.html { redirect_to edit_intranet_folheto_path("1"), notice: 'Folheto atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @folheto }
      else
        format.html { render :edit }
        format.json { render json: @folheto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /folhetos/1
  # DELETE /folhetos/1.json
  def destroy
    @folheto.destroy
    respond_to do |format|
      format.html { redirect_to new_intranet_folheto_path, notice: 'Folheto deletado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_folheto
      @folheto = Folheto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def folheto_params
      params.require(:folheto).permit(:link_video, :imagem_folheto)
    end
end

public_html/intranet/app/controllers/intranet/intranet_controller.rb
class Intranet::IntranetController < ApplicationController
  layout "intranet"
  before_action :authorize
  protect_from_forgery

  protected
  def authorize
    unless User.find_by(id: session[:user_id])
      redirect_to intranet_login_url, alert: "Você precisa fazer o login para acessar!"
    end
  end

  def sort_column
    params[:sort] || "id"
  end

  def sort_direction
    params[:direction] || "desc"
  end
end

public_html/intranet/app/controllers/intranet/sessions_controller.rb
class Intranet::SessionsController < Intranet::IntranetController
  skip_before_action :authorize
  layout "intranet_login"

  def index
    @sessions = Session.all
  end


  def new
  end

  def create
    user = User.find_by(name: params[:name])
    if user and user.authenticate(params[:password])
      session[:user_id] = user.id
      session[:user_name] = user.name
      redirect_to intranet_dashboard_index_path, alert: "Login efetuado com sucesso!"
    else
      redirect_to intranet_login_url, alert: "Usuário ou Senha inválidos!"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to intranet_login_url, alert: "Você saiu com sucesso!"
  end
end

public_html/intranet/app/helpers/users_helper.rb
module UsersHelper
end

public_html/intranet/app/views/intranet/users/_form.html.erb
<div class="">

  <div class="clearfix"></div>

  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <%= form_for [:intranet, @user], html: { :novalidate=> true,:class=>"form-horizontal form-label-left" } do |f| %>

          <span class="section">Usuário</span>

          <div class="text-center">
            <% if @user.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

              <ul style="list-style: none;">
                <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
                <% end %>
              </ul>
            </div>
            <% end %>
          </div>


          <div class="item form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Nome <span class="required">*</span>
            </label>
            <div class="col-md-6 col-sm-6 col-xs-12">
              <%= f.text_field :name , :class=>"form-control col-md-7 col-xs-12", :data=> {"validate-length-range"=>"2", "validate-words"=>"1"}, :placeholder=>"Digite o nome", :required=> true %>
            </div>
          </div>
          <div class="item form-group">
            <label for="password" class="control-label col-md-3">Senha</label>
            <div class="col-md-6 col-sm-6 col-xs-12">
              <%= f.password_field :password,:class=>"form-control col-md-7 col-xs-12", :required=> true %>
            </div>
          </div>
          <div class="item form-group">
            <label for="password2" class="control-label col-md-3 col-sm-3 col-xs-12">Confirme a senha</label>
            <div class="col-md-6 col-sm-6 col-xs-12">
              <%= f.password_field :password_confirmation, :class=>"form-control col-md-7 col-xs-12", :required=> true %>
            </div>
          </div>


          <div class="ln_solid"></div>
          <div class="form-group">
            <div class="col-md-6 col-md-offset-3">
              <a href="<%= intranet_users_path %>">
                <button type="submit" class="btn btn-primary">Cancelar</button>
              </a>
              <%= f.submit "Salvar", :class=>"btn btn-success" %>
              <!-- <button id="send" type="submit" class="btn btn-success">Salvar</button> -->
            </div>
          </div>
          <%end%>
        </div>
      </div>
    </div>
  </div>
</div>

public_html/intranet/app/views/intranet/users/edit.html.erb
<h1>Editar Usuário</h1>


<%= render 'form' %>

public_html/intranet/app/views/intranet/users/index.html.erb
<div class="">
  <div class="page-title">
    <div class="title_left">
      <h3>Usuários</h3>
    </div>

    <div class="title_right">
      <a href="<%= new_intranet_user_path %>">
        <button type="button" class="pull-right btn btn-round btn-primary"><i class="fa fa-plus"></i> Novo</button>
      </a>

    </div>
  </div>

  <div class="clearfix"></div>

  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <div class="clearfix"></div>
        </div>
        <div class="x_content">

          <div class="text-center">
            <% if notice %>
            <p id="notice" class="bg-green"><%= notice %></p>
            <%end%>
          </div>
          <table id="datatable" class="table table-striped table-bordered">
            <thead>
              <tr>
                <th>Nome</th>
                <th class="col-xs-1">Editar</th>
                <th class="col-xs-1">Excluir</th>
              </tr>
            </thead>


            <tbody>
              <% @users.each do |user| %>
              <tr>
                <td><%= user.name %></td>
                <td><%= link_to ("<i class='fa fa-edit'></i>".html_safe), edit_intranet_user_path(user) %></td>
                <td><%= link_to ("<i class='fa fa-close'></i>".html_safe), intranet_user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>

  </div>
</div>

public_html/intranet/app/views/intranet/users/new.html.erb
<h1>Novo Usuário</h1>

<%= render 'form' %>