public_html/config/routes.rb
Rails.application.routes.draw do

  resources :capa
  resources :pesquisa
  resources :empresarial
  resources :especializada
  resources :academica
  resources :equipe
  resources :artigos
  resources :publicacoes
  resources :mapa

  root 'capa#index'
  post 'interesse' => 'capa#createinteresse'
  post 'update_dashboard' => 'intranet/dashboard#update_index'
  get 'intranet' => 'intranet/sessions#new'
  namespace :intranet do
    resources :kind_of_posts do
      resources :posts
    end
    resources :users
    resources :posts
    resources :categories
    resources :dashboard
    resources :folhetos
    resources :clientes

    controller :sessions do
      get  'login' => :new
      post 'login' => :create
      delete 'logout' => :destroy
    end

    get 'sessions/create'
    get 'sessions/destroy'

    get 'admin' => 'admin#index'
    get 'logout' => 'sessions#destroy'

  end
  mount Ckeditor::Engine => '/ckeditor'

end

public_html/app/models/folheto.rb
class Folheto < ActiveRecord::Base

  has_attached_file :imagem_folheto, :styles =>{ :thumb =>"158x69#", :medium =>"#754x" }
  do_not_validate_attachment_file_type :imagem_folheto

  def remover_imagem_folheto(remover)
    self.imagem_folheto.destroy if remover
  end


end

public_html/app/controllers/intranet/admin_controller.rb
class Intranet::AdminController < Intranet::IntranetController
  before_action :authorize
  def index
  end
end

public_html/app/controllers/intranet/capa_controller.rb
class Intranet::CapaController < Intranet::IntranetController
  before_action :authorize
  protect_from_forgery except: [:update_index]


  def index
    @date_filter = "30_dias"
    @visitors_by_date = nil
    @visitors = nil
    @sessions = nil
    @pageviews =  nil
    @avg_duration = nil
  end

  def update_index


    require 'google/api_client'
    require 'date'

    @date_filter = params[:date]
    service_account_email = 'analytics-intranet@api-project-359628520071.iam.gserviceaccount.com' # Email of service account
    key_file = 'config/API Project-6186e14a5b0a.p12' # File containing your private key
    key_secret = 'notasecret' # Password to unlock private key
    profile = 'ga:18033085' # Analytics profile ID.
    @client_id = 'ga:18033085'
    client = Google::APIClient.new(
      :application_name => 'API Project',
      :application_version => '1.0')

    key = Google::APIClient::KeyUtils.load_from_pkcs12(key_file, key_secret)
    client.authorization = Signet::OAuth2::Client.new(
        :token_credential_uri => 'https://accounts.google.com/o/oauth2/token',
        :audience => 'https://accounts.google.com/o/oauth2/token',
        :scope => 'https://www.googleapis.com/auth/analytics.readonly',
        :issuer => service_account_email,
        :signing_key => key)

    client.authorization.fetch_access_token!

    analytics = client.discovered_api('analytics','v3')

    if @date_filter == '30_dias'
      # start_date = Time.now - 1.month
      start_date = Date.today.last_month.strftime("%Y-%m-%d").to_s
      end_date = Date.today.strftime("%Y-%m-%d").to_s
      dimension = "ga:date"
    elsif @date_filter == '7_dias'
      start_date = Date.today.last_week.strftime("%Y-%m-%d").to_s
      end_date = Date.today.strftime("%Y-%m-%d").to_s
      dimension = "ga:date"
    else
      start_date = Date.yesterday.strftime("%Y-%m-%d").to_s
      end_date = Date.yesterday.strftime("%Y-%m-%d").to_s
      dimension = "ga:hour"
    end

    result = client.execute(:api_method => analytics.data.ga.get, :parameters => {
        'ids'        => profile,
        'start-date' => start_date,
        'end-date'   => end_date,
        'metrics'    => 'ga:visitors,ga:sessions,ga:pageviews,ga:avgSessionDuration',
    })
    result2 =  client.execute(:api_method => analytics.data.ga.get, :parameters => {
        'ids'        => profile,
        'start-date' => start_date,
        'end-date'   => end_date,
        'dimensions' => dimension,
        'metrics'    => 'ga:visitors',
    })


    @visitors_by_date = result2.data.rows

    @visitors = result.data.totalsForAllResults["ga:visitors"]
    @sessions = result.data.totalsForAllResults["ga:sessions"]
    @pageviews =  result.data.totalsForAllResults["ga:pageviews"]
    @avg_duration =  Time.at(result.data.totalsForAllResults["ga:avgSessionDuration"].to_f).utc.strftime("%H:%M:%S")

    respond_to do |format|
      format.js
    end

  end

end

public_html/app/controllers/intranet/categories_controller.rb
class Intranet::CategoriesController < Intranet::IntranetController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :authorize
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to intranet_categories_url, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to intranet_categories_url, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to intranet_categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :inativar, :Kind_of_post_id)
    end
end

public_html/app/controllers/intranet/clientes_controller.rb
class Intranet::ClientesController < Intranet::IntranetController

  before_action :authorize, except: [:create_from_contact]
  helper_method :sort_column, :sort_direction
  protect_from_forgery except: [:create_from_contact]

  #STATUS DO CLIENTE:   Aberto:  1
  #                     Em atendimento: 2
  #                     Encerrado: 3
  #                     Fechado: 4

  def index


    sort_column = params[:sort]
    sort_direction = params[:direction]
    @de = params[:de]
    @ate = params[:ate]
    @atendido_por = params[:atendido_por]
    @status = params[:status]
    @search = params[:search]
    if sort_direction == 'desc'
      @clientes = Cliente.search(params[:search]).order("#{sort_column} desc").search_status(@status).search_atendente(@atendido_por).search_data(@de,@ate).page(params[:page])
    elsif sort_direction == 'asc'
      @clientes = Cliente.search(params[:search]).order("#{sort_column} asc").search_status(@status).search_atendente(@atendido_por).search_data(@de,@ate).page(params[:page])
    else
      @clientes = Cliente.search(params[:search]).order("created_at desc").search_status(@status).search_atendente(@atendido_por).search_data(@de,@ate).page(params[:page])
    end

    respond_to do |format|
      format.html
      format.js
      format.pdf do
        data_de = @de.nil? ? "01/01/2016" : @de
        data_ate = @ate.nil? ? Time.now.strftime("%d/%m/%Y") : @ate
        pdf = Prawn::Document.new
        relatorio(pdf, data_de, data_ate ,@clientes)
        send_data pdf.render, filename: 'relatorio.pdf', type: 'application/pdf'
      end


    end



  end

  def relatorio(pdf, data_de, data_ate, clientes) # geração de relatorio para download

    pdf.image "#{Rails.root}/app/assets/images/logomarca-criativitta-menu.png", width: 130, height: 33, position: 405, vposition: 10
    pdf.text "RELATÓRIO DE LEADS - CRIATIVITTÁ"
    pdf.stroke_horizontal_rule
    pdf.move_down 20
    pdf.text "Período: " + data_de + " até " + data_ate
    pdf.move_down 20
    pdf.font_size 8

    data = [["Data", 'Nome', 'Telefone', 'Email', 'Interesse', 'Atendente', 'Status']]

    clientes.each do |c|
      status = ""
      case c.status
      when 1
        status = "Aberto"
      when 2
        status = "Em atendimento"
      when 3
        status = "Encerrado"
      when 4
        status = "Fechado"
      end
      data += [[c.created_at.strftime("%d/%m/%Y"), c.nome, c.telefone, c.email, c.interesse, c.atendido_por, status]]
    end

    pdf.table(data, header: true, column_widths: [55] )

  end



  def show
    @cliente = Cliente.find(params[:id])
  end

  def new
    @cliente = Cliente.new
  end

  def edit
    @cliente = Cliente.find(params[:id])
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to intranet_clientes_url, notice: 'Cliente foi criado com sucesso' }
        format.json { render action: 'show', status: :created, location: @cliente }
        format.js
      else
        format.html { render action: 'new' }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  def create_from_contact
    # implementar de acordo com os parametros que vier da view
    @curso_id = params[:id][0]
    @categoria_id = params[:categoria_id][0]
    @cliente = Cliente.new(cliente_params)

    if @cliente.valid?
      if verify_recaptcha(model: @cliente)
        if @cliente.save
          ContatoMailer.contato(@cliente.nome,@cliente.telefone,@cliente.email,@cliente.mensagem, @cliente.curso).deliver
          redirect_to  "/cursos/#{@curso_id}?id=#{@categoria_id}", notice: "Mensagem enviada com successo!"
        end
      else
        flash[:error] = "Por favor marque a opção 'Não sou um robô' antes de enviar."
        redirect_to "/cursos/#{@curso_id}?id=#{@categoria_id}"

      end
    else
      flash[:alert] = 'Alguns campos não foram preenchidos corretamente.'
      redirect_to "/cursos/#{@curso_id}?id=#{@categoria_id}"
    end
  end

  def update
    @cliente = Cliente.find(params[:id])

    if @cliente.update_attributes(cliente_params)
      redirect_to intranet_clientes_url, notice: 'Cliente atualizado com sucesso.'
    else
      render action: "edit"
    end
  end

  def destroy
    @cliente = Cliente.find(params[:id])
    @cliente.destroy

    redirect_to intranet_clientes_url, notice: 'Cliente excluido com sucesso.'
  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_cliente
    @cliente = Cliente.find(params[:id])
  end
  def sort_column
    params[:sort] || "id"
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def cliente_params
    params.require(:cliente).permit(:nome, :email, :telefone, :mensagem, :interesse, :status, :atendido_por)
  end

end

public_html/app/controllers/intranet/dashboard_controller.rb
class Intranet::DashboardController < Intranet::IntranetController

  before_action :authorize
  protect_from_forgery except: [:update_index]


  def index



    @date_filter = "30_dias"



    @visitors_by_date = nil

    @visitors = nil
    @sessions = nil
    @pageviews =  nil
    @avg_duration = nil

  end

  def update_index


    require 'google/api_client'
    require 'date'

    @date_filter = params[:date]
    service_account_email = 'analytics-intranet@api-project-359628520071.iam.gserviceaccount.com' # Email of service account
    key_file = 'config/API Project-6186e14a5b0a.p12' # File containing your private key
    key_secret = 'notasecret' # Password to unlock private key
    profile = 'ga:248169208' # Analytics profile ID = Criativittá.
    client = Google::APIClient.new(
      :application_name => 'API Project',
      :application_version => '1.0')

    key = Google::APIClient::KeyUtils.load_from_pkcs12(key_file, key_secret)
    client.authorization = Signet::OAuth2::Client.new(
        :token_credential_uri => 'https://accounts.google.com/o/oauth2/token',
        :audience => 'https://accounts.google.com/o/oauth2/token',
        :scope => 'https://www.googleapis.com/auth/analytics.readonly',
        :issuer => service_account_email,
        :signing_key => key)

    client.authorization.fetch_access_token!

    analytics = client.discovered_api('analytics','v3')

    if @date_filter == '30_dias'
      start_date = Date.today.last_month.strftime("%Y-%m-%d").to_s
      end_date = Date.today.strftime("%Y-%m-%d").to_s
      dimension = "ga:date"
    elsif @date_filter == '7_dias'
      start_date = Date.today.last_week.strftime("%Y-%m-%d").to_s
      end_date = Date.today.strftime("%Y-%m-%d").to_s
      dimension = "ga:date"
    else
      start_date = Date.yesterday.strftime("%Y-%m-%d").to_s
      end_date = Date.yesterday.strftime("%Y-%m-%d").to_s
      dimension = "ga:hour"
    end

    result = client.execute(:api_method => analytics.data.ga.get, :parameters => {
        'ids'        => profile,
        'start-date' => start_date,
        'end-date'   => end_date,
        'metrics'    => 'ga:users,ga:sessions,ga:pageviews,ga:avgSessionDuration',
    })
    result2 =  client.execute(:api_method => analytics.data.ga.get, :parameters => {
        'ids'        => profile,
        'start-date' => start_date,
        'end-date'   => end_date,
        'dimensions' => dimension,
        'metrics'    => 'ga:users',
    })


    @visitors_by_date = result2.data.rows

    @visitors = result.data.totalsForAllResults["ga:users"]
    @sessions = result.data.totalsForAllResults["ga:sessions"]
    @pageviews =  result.data.totalsForAllResults["ga:pageviews"]
    @avg_duration =  Time.at(result.data.totalsForAllResults["ga:avgSessionDuration"].to_f).utc.strftime("%H:%M:%S")

    respond_to do |format|
      format.js
    end

  end


end

public_html/app/controllers/intranet/folhetos_controller.rb
class Intranet::FolhetosController < Intranet::IntranetController
  before_action :authorize
  before_action :set_folheto, only: [:show, :edit, :update, :destroy]

  # GET /folhetos
  # GET /folhetos.json
  def index
    @folhetos = Folheto.all
  end

  # GET /folhetos/1
  # GET /folhetos/1.json
  def show
  end

  # GET /folhetos/new
  def new
    @folheto = Folheto.new
  end

  # GET /folhetos/1/edit
  def edit
  end

  # POST /folhetos
  # POST /folhetos.json
  def create
    @folheto = Folheto.new(folheto_params)

    respond_to do |format|
      if @folheto.save
        format.html { redirect_to new_intranet_folheto_path, notice: 'Folheto criado com sucesso.' }
        format.json { render :show, status: :created, location: @folheto }
      else
        format.html { render :new }
        format.json { render json: @folheto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /folhetos/1
  # PATCH/PUT /folhetos/1.json
  def update
    @folheto.remover_imagem_folheto(params[:remover_imagem_folheto])
    respond_to do |format|
      if @folheto.update(folheto_params)
        format.html { redirect_to edit_intranet_folheto_path("1"), notice: 'Folheto atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @folheto }
      else
        format.html { render :edit }
        format.json { render json: @folheto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /folhetos/1
  # DELETE /folhetos/1.json
  def destroy
    @folheto.destroy
    respond_to do |format|
      format.html { redirect_to new_intranet_folheto_path, notice: 'Folheto deletado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_folheto
      @folheto = Folheto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def folheto_params
      params.require(:folheto).permit(:link_video, :imagem_folheto)
    end
end

public_html/app/controllers/intranet/intranet_controller.rb
class Intranet::IntranetController < ApplicationController
  layout "intranet"
  before_action :authorize
  protect_from_forgery

  protected
  def authorize
    unless User.find_by(id: session[:user_id])
      redirect_to intranet_login_url, alert: "Você precisa fazer o login para acessar!"
    end
  end

  def sort_column
    params[:sort] || "id"
  end

  def sort_direction
    params[:direction] || "desc"
  end
end

public_html/app/controllers/intranet/sessions_controller.rb
class Intranet::SessionsController < Intranet::IntranetController
  skip_before_action :authorize
  layout "intranet_login"

  def index
    @sessions = Session.all
  end


  def new
  end

  def create
    user = User.find_by(name: params[:name])
    if user and user.authenticate(params[:password])
      session[:user_id] = user.id
      session[:user_name] = user.name
      redirect_to intranet_dashboard_index_path, alert: "Login efetuado com sucesso!"
    else
      redirect_to intranet_login_url, alert: "Usuário ou Senha inválidos!"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to intranet_login_url, alert: "Você saiu com sucesso!"
  end
end

public_html/app/helpers/folhetos_helper.rb
module FolhetosHelper
end

public_html/app/views/intranet/folhetos/_form.html.erb
<div class="modal fade" id="modal-alert" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Alerta</h4>
      </div>

      <div class="modal-body">
        <p id="texto_alerta"></p>
        <p class="debug-url"></p>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Ok</button>
      </div>
    </div>
  </div>
</div>

<div class="col-md-12 col-xs-12">

  <div class="text-center">
    <% if notice %>
    <script type="text/javascript">
    $(document).ready(function(){

      $("#notice").fadeIn();
      setTimeout(function(){
        $("#notice").fadeOut(1000);
      }, 3000);

    });
    </script>
    <p id="notice" class="bg-green" style="display: none;"><%= notice %></p>
    <%end%>
  </div>


  <div class="x_panel">

    <%= form_for [:intranet, @folheto], html: { :multipart=> true , :novalidate=>"novalidate", :data=>{"parsley-validate"=>"true"},:class=>"form-horizontal form-label-left", :id=>"formulario" } do |f| %>
    <div class="x_title">
      <h2>Folheto</h2>
      <ul class="nav navbar-right panel_toolbox">
      </ul>
      <div class="clearfix"></div>
    </div>
    <div class="col-md-6 col-xs-12">

      <div class="x_content">
        <br />

        <div class="text-center">
          <% if @folheto.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@folheto.errors.count, "erro") %> no preenchimento do fomulário:</h2>

            <ul style="list-style: none;color: #f00;">
              <% @folheto.errors.full_messages.each do |message| %>
              <li><%= message %></li>
              <% end %>
            </ul>
          </div>
          <% end %>
        </div>


        <div class="form-group">
          <label class="control-label col-md-3 col-sm-3 col-xs-12">Tipo de folheto</label>
          <div class="col-md-9 col-sm-9 col-xs-12">
            <select class="form-control" onchange="Change(this)" id="select_tipos_folheto">
              <option>Imagem</option>
              <option>Vídeo</option>
            </select>
          </div>
        </div>


        <div class="form-group" id="folheto_video" style="display: none;">
          <label class="control-label col-md-3 col-sm-3 col-xs-12">
            Link do vídeo
          </label>
          <div class="col-md-9 col-sm-9 col-xs-12">
            <%= f.text_field :link_video , :class=>"form-control col-md-7 col-xs-12", :id=>"text_video_folheto", :placeholder=>"Informe o link do vídeo no youtube" %>
          </div>
          <span style="margin-left: 26.5%;font-size: 11px !important;"> * (Utilizar somente a parte em negrito do link. Ex: www.youtube.com/watch?v=<span style="color: black; font-weight: bolder; font-size:12px;">M6yg7kJb-eY</span>)</span>
        </div>

        <div id="folheto_imagem">

          <div class="form-group" style="margin-bottom: 5px;">
            <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
            <div class="col-md-9 col-sm-9 col-xs-12">
              <% if f.object.imagem_folheto? %>

              <div class="">
                <div class="">
                  <div class="image view">
                    <%= f.hidden_field :id %>

                    <%= image_tag f.object.imagem_folheto.url(:medium), :style=>"width: 100%; display: block;", :class=>"imagem_folheto" %>
                  </div>
                  <div class="caption">
                    <div class="checkbox">
                      <label class="checkbox-remove-image-folheto">
                        <% unless f.object.imagem_folheto.blank? %>
                        <%= check_box_tag :remover_imagem_folheto, 'yes', false, :class=>"flat" %> Remover imagem
                        <% end %>
                      </label>
                    </div>
                    <p></p>
                  </div>
                </div>
              </div>
              <% end %>
            </div>
          </div>


          <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
            <div class="col-md-9 col-sm-9 col-xs-12">
              <div class="input-group">
                <label class="input-group-btn" title="Importar imagem">
                  <span class="btn btn-primary">
                    <%# f.file_field :imagem, :class => 'campos_intranet' %>
                    Arquivo&hellip; <%= f.file_field :imagem_folheto,
                    :class => 'fileupload campos_intranet field_galeria',
                    :style=>"display: none;",
                    :onchange=>"galeria_change_file(this)" %>
                  </span>
                </label>
                <input type="text" name="galeria_text-file" class="form-control text_file_galeria" value="Nenhum arquivo selecionado" readonly>
              </div>
            </div>
            <span style="margin-left: 26.5%;font-size: 12px !important;">* (Arquivo JPG / Dimensão Máxima 1200x1200px / Peso 250kb).</span>
          </div>
        </div>


      </div>
      <!-- end x_content -->
    </div>


    <div class="col-md-12 col-sm-12 col-xs-12">

      <div class="x_content">
        <br />

        <div class="ln_solid"></div>
        <div class="form-group fixed-position-btns">
          <div class="text-center">
            <!-- <a href="#">
              <button type="button" class="btn btn-primary">Cancel</button>
            </a> -->
            <button id="send" type="submit" class="btn btn-success" onclick="submit_form()">Salvar</button>
          </div>
        </div>

      </div>
      <!-- end x_content -->
    </div>

    <% end %>

  </div>



</div>


<script type="text/javascript">

$(document).ready(function() {
  var tem_imagem = $(".imagem_folheto")[0];
  var tem_video = document.getElementById("text_video_folheto").value;

  if (tem_imagem != undefined) {
    document.getElementById("select_tipos_folheto").selectedIndex = "0";
    $("#folheto_video").css("display","none");
    $("#folheto_imagem").css("display","block");
  }
  if (tem_video.length != 0) {
    document.getElementById("select_tipos_folheto").selectedIndex = "1";
    $("#folheto_video").css("display","block");
    $("#folheto_imagem").css("display","none");
  }
});

// altera o nome do input text para o nome da imagem selecionada no input file
function galeria_change_file(field){
  // var className = $(".fileupload");
  document.getElementsByName('galeria_text-file')[0].value = field.value.replace(/\\/g, '/').replace(/.*\//, '');
}

// mostra a imagem quando selecionada no input file
$("#inputImage").change(function(){
  change_file();
  readURL(this);
});
$("#imgInp").change(function(){
  readURL(this);
});
function submit_form(){
  document.getElementById("formulario").submit();
}
function Change(option){
  var opcao = option.value.toLowerCase();
  var tem_imagem = $(".imagem_folheto")[0];
  var tem_video = document.getElementById("text_video_folheto").value;

  // alert("tem_video.length = " + tem_video.length);
  if (opcao == "imagem") {
    if (tem_video.length != 0) {
      $( "p#texto_alerta" ).html( "O folheto possui vídeo cadastrado. <br>Deixe em branco o link do vídeo e salve para poder adicionar uma imagem." );
      $('#modal-alert').modal('show');
      // alert("O folheto permite somente 1 imagem ou 1 vídeo!");
      document.getElementById("select_tipos_folheto").selectedIndex = "1";
      $("#folheto_video").css("display","block");
      $("#folheto_imagem").css("display","none");
    }else {
      // alert("video NÃO existe");
      // alert("Selecionou imagem");
      $("#folheto_video").css("display","none");
      $("#folheto_imagem").css("display","block");
    }
  }
  if (opcao == "vídeo" ) {
    if (tem_imagem != undefined) {
      $( "p#texto_alerta" ).html( "O folheto possui imagem cadastrada. <br>Clique em remover imagem e salve para poder adicionar o link de um vídeo." );
      $('#modal-alert').modal('show');

      // alert("O folheto permite somente 1 imagem ou 1 vídeo!");
      document.getElementById("select_tipos_folheto").selectedIndex = "0";
      $("#folheto_video").css("display","none");
      $("#folheto_imagem").css("display","block");
    }else {
      // alert("Imagem NÃO existe");
      // alert("Selecionou video");
      $("#folheto_video").css("display","block");
      $("#folheto_imagem").css("display","none");
    }
  }
}
</script>

public_html/app/views/intranet/folhetos/edit.html.erb
<h1>Editar</h1>

<%= render 'form' %>

public_html/app/views/intranet/folhetos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Folhetos</h1>

<table>
  <thead>
    <tr>
      <th>Link video</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @folhetos.each do |folheto| %>
      <tr>
        <td><%= folheto.link_video %></td>
        <td><%= link_to 'Show', folheto %></td>
        <td><%= link_to 'Edit', edit_intranet_folheto_path(folheto) %></td>
        <td><%= link_to 'Destroy', intranet_folheto_path(folheto), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Folheto', new_intranet_folheto_path %>

public_html/app/views/intranet/folhetos/new.html.erb
<h1>Cadastrar</h1>

<%= render 'form' %>

public_html/app/views/intranet/folhetos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Link video:</strong>
  <%= @folheto.link_video %>
</p>

<%= link_to 'Edit', edit_folheto_path(@folheto) %> |
<%= link_to 'Back', folhetos_path %>